### ISSUE TITLE
Suggest GH Pages Demo

### ISSUE THREAD

**Issue by faceleg** [VinceG/Bootstrap-Admin-Theme#1]
I've made one here: http://faceleg.github.com/Bootstrap-Admin-Theme/

I am unable to create a pull request as the `gh-pages` branch doesn't exist on your side.

To replicate the Github pages page I made, you could either follow this guide: https://help.github.com/articles/creating-project-pages-manually or create a `gh-pages` branch, after which I can open a pull request.

**Comment by VinceG** [comment]
Thank You. I'll add a gh-pages repository this weekend so we can have a live example of the theme.

**Comment by VinceG** [comment]
Added gh-pages branch.

http://vinceg.github.com/Bootstrap-Admin-Theme

Thanks.
