### ISSUE TITLE
Is that compatible to bootstrap v3

### ISSUE THREAD

**Issue by dlnufox** [VinceG/Bootstrap-Admin-Theme#10]
hello, I wanna to know that is your project compatible to the boorstrap v3 ? If I change the bootstrap 2.3.3 to the the latest version of the bootstrap, would the project has some problem ?

**Comment by VinceG** [comment]
@dlnufox Not Compatible.

**Comment by sbefort** [comment]
This is a really awesome template you have here.  Any plans to make it compatible with v3?

**Comment by VinceG** [comment]
@sbefort There are plans to make a V3 version. I just need to find the time.

**Comment by ivantcholakov** [comment]
There is an effort on Bootstrap 3 implementation https://github.com/meritoo/Bootstrap-3-Admin-Theme , but it needs polishing, for Opera at least.

**Comment by VinceG** [comment]
@sbefort @dlnufox just in case you did not notice there is a v3 version now.
