### ISSUE TITLE
Element stacks

### ISSUE THREAD

**Issue by yugo412** [VinceG/Bootstrap-Admin-Theme#12]
I had a problem using group buttons in table. Like this picture. 

![dropdown-button](https://f.cloud.github.com/assets/477311/1606737/268e7df2-5456-11e3-9a4c-94ba375b2b88.PNG)

I'm trying to add z-index:-1 to .block-content class, but it's not working. :(
How to solve this problem?

Thank you.

**Comment by VinceG** [comment]
This is unrelated to this repository and the theme. you'll need to specify the position of the dropdown by adding a class 'dropup' see:

http://getbootstrap.com/2.3.2/components.html#buttonDropdowns

**Comment by VinceG** [comment]
@arvernester
