### ISSUE TITLE
Dropdown menu on mobile

### ISSUE THREAD

**Issue by ghost** [VinceG/Bootstrap-Admin-Theme#16]
I do not see the dropdown menu right of the search on my mobile (Android, Galaxy Note 3).

The search is displayed.

Where I can change this? I looked into css/ and bootstrap/css/ but did not found anything.

**Comment by VinceG** [comment]
Theme does not work well in mobile devices. but the navigation bar is present.

![screen shot 2014-05-22 at 9 35 50 pm](https://cloud.githubusercontent.com/assets/195199/3063112/c6283fc2-e233-11e3-9dba-3cabe4717d6d.png)
