### ISSUE TITLE
Clarify 2.x vs 3.x

### ISSUE THREAD

**Issue by mgraham** [VinceG/Bootstrap-Admin-Theme#17]
Thank you for a great theme, and for making it open source!

This may sound like a stupid suggestion, but two people in our organization thought that this version was the Bootstrap 3.x version.  The link in the readme looks like a heading, not like a link to another project.

I recommend changing the text to not look like a heading, and changing the wording to something like:  "The Bootstrap 3.x version can be found here"

**Comment by VinceG** [comment]
@mgraham Thank You. updated.
