### ISSUE TITLE
Consider removing repo?

### ISSUE THREAD

**Issue by dandv** [VinceG/Bootstrap-Admin-Theme#19]
Since this is for Bootstrap 2, and new projects would either consider the Bootstrap 3 version, or one of the actively maintained templates, e.g.
- https://github.com/almasaeed2010/AdminLTE

**Comment by VinceG** [comment]
@dandv why would i remove it though? there are hundreds of free templates out there, both for bootstrap 2 and 3 this is just another one. with nearly 1000 stars i don't think removing this is a good idea.

**Comment by dandv** [comment]
To reduce the search space for Bootstrap admin templates.
