### ISSUE TITLE
Submit validate form

### ISSUE THREAD

**Issue by Mostro69** [VinceG/Bootstrap-Admin-Theme#20]
Hi, I´m new in this, i use your template to create a form, but it validates but it desn´t submit, please help

**Comment by herlon214** [comment]
@Mostro69, can you show us the code?

**Comment by hkakembo** [comment]
sorry guys have no idea of what's happening with my account, new here. i dont happen to see that repository.

**Comment by VinceG** [comment]
closed due to lack of information. please re-open when you have more info. @Mostro69
