### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by schmunk42** [VinceG/Bootstrap-Admin-Theme#3]
Under which license is your theme?

**Comment by VinceG** [comment]
MIT. added the license.

**Comment by VinceG** [comment]
@schmunk42

**Comment by schmunk42** [comment]
Thanks! Btw, this issue came up here: http://www.yiiframework.com/forum/index.php/topic/44425-advanced-application-backend-template/ 
You're very welcome if you'd like to join the conversation.

**Comment by VinceG** [comment]
Thanks @schmunk42
