### ISSUE TITLE
idea: add more standard pages like in paid themes

### ISSUE THREAD

**Issue by shimondoodkin** [VinceG/Bootstrap-Admin-Theme#4]
edit list,edit item, new item,sign up login,profile...
http://portnine.com/bootstrap-themes

**Comment by VinceG** [comment]
we have a login screen:
http://vinceg.github.io/Bootstrap-Admin-Theme/login.html

sign up will probably be the same as login with a few additional fields.

what is "edit list,edit item, new item" ?

I think a theme should include different kind of pages based on usage scenarios such as a page that displays various tables, page that displays various charts, page that displays various form elements etc...

I have a few pages planned that include: Tables, Gallery, File Upload, Rich Editors. I am constantly looking to add more pages based on different commercial templates i see out there and the popularity of items.

If you have a suggestion please be more specific. 

Thanks.

**Comment by shimondoodkin** [comment]
list: http://portnine.com/bootstrap/WintertideAdmin/build/users.html
edit item: http://portnine.com/bootstrap/WintertideAdmin/build/user.html

**Comment by VinceG** [comment]
List looks like a table, which i am planning on adding a page that will show different kind of tables and usage including data tables.

Edit item looks like a normal page with some form fields, you can use the current form fields example page to do just that.

**Comment by shimondoodkin** [comment]
ok
