### ISSUE TITLE
chart-bottom-heading not correctly centered!

### ISSUE THREAD

**Issue by sancamac** [VinceG/Bootstrap-Admin-Theme#5]
hi!
im using this awesome Admin-Theme, and just found that the easypiechart canvas is not correctly centered on the parent div.
a solution for that is to modify this file:
Admin-Theme>Vendors>easypiechart>jquery.easy-pie-chart.css

and add to the class: .easyPieChart {}
this line: margin: 0px auto;

and then to center the chart-bottom-heading go to:
Admin-Theme>Assets>styles.css

and replace the class .chart-bottom-heading with:
.chart-bottom-heading {
    margin-top: 5px;
  text-align: center;
}

Thank you very much, and sorry for bothering!
Cheers

**Comment by VinceG** [comment]
@sacamacho not sure if i feel comfortable editing the source file jquery.easy-pie-chart.css that comes with the library. Editing source files is never a good idea. I've updated the styles.css file and added the . easyPieChart css class with the margin: 0px auto; and updated the chart-bottom-heading class with the suggested above.

That fixed it.
