### ISSUE TITLE
Upgrade to bootstrap 3.0

### ISSUE THREAD

**Issue by Jomaanro** [VinceG/Bootstrap-Admin-Theme#6]
The current lay-out seems not be compatible with the the latest version of bootstrap. It is still in RC2 but maybe good to already have a look at it.

**Comment by VinceG** [comment]
I'll be making a new version of the admin bootstrap panel for the 3.0 version. @Jomaanro

**Comment by mrbormeth** [comment]
Nice m8! :D Cant wait!
